# Generated by Django 3.2.4 on 2021-06-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrmanager',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
