# Generated by Django 3.2.4 on 2021-06-03 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0003_alter_hrmanager_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hrmanager',
            name='cnic',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
