# Generated by Django 3.2.4 on 2021-06-03 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0004_alter_hrmanager_cnic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrmanager',
            name='create_at',
        ),
    ]
